# This rule is not used by the project kubetimeline itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the timeline.thinnesen.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubetimeline
    app.kubernetes.io/managed-by: kustomize
  name: kubetimeline-editor-role
rules:
- apiGroups:
  - timeline.thinnesen.com
  resources:
  - kubetimelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - timeline.thinnesen.com
  resources:
  - kubetimelines/status
  verbs:
  - get
