# This rule is not used by the project kubetimeline itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over timeline.thinnesen.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubetimeline
    app.kubernetes.io/managed-by: kustomize
  name: kubetimeline-admin-role
rules:
- apiGroups:
  - timeline.thinnesen.com
  resources:
  - kubetimelines
  verbs:
  - '*'
- apiGroups:
  - timeline.thinnesen.com
  resources:
  - kubetimelines/status
  verbs:
  - get
