---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - timeline.thinnesen.com
  resources:
  - kubetimelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - timeline.thinnesen.com
  resources:
  - kubetimelines/finalizers
  verbs:
  - update
- apiGroups:
  - timeline.thinnesen.com
  resources:
  - kubetimelines/status
  verbs:
  - get
  - patch
  - update
